server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    org.hibernate.jpa: DEBUG
  pattern:
    console: '%-29(%d{hh:mm:ss.SSS} [%thread]) %-5.5level{5} %-36.36logger{36} %msg%n'

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/mcp
    username: root
    password: sasa
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false

  jackson:
    serialization:
      fail-on-empty-beans: false

mcp:
  json-url: https://raw.githubusercontent.com/vas-test/test1/master/logs/

word-list: YOU, ARE, FINE, HELLO, NOT
 
